import {
  Envelope,
  PlusCircle,
  CaretLeft,
  ArrowLineRight,
  CaretRight,
  ArrowLineLeft,
  Basket,
  XCircle,
  CheckFat,
  ListChecks,
  X,
  Copy,
  Trash,
  CheckCircle,
  Pencil,
  CaretUp,
  CaretDown,
  FacebookLogo,
  NewspaperClipping,
  FileText,
  Files,
  FileCsv,
  FileArrowDown,
  FileArrowUp,
  FileXls,
  Funnel,
  Prohibit,
  NotePencil,
  Chats,
  Users,
  HouseLine,
  Image,
  Info,
  Link,
  MapPin,
  Lock,
  SignIn,
  SignOut,
  List,
  Money,
  Handshake,
  LockKeyOpen,
  Pause,
  HandCoins,
  Package,
  Question,
  ArrowCounterClockwise,
  Star,
  MagnifyingGlass,
  ListMagnifyingGlass,
  Detective,
  ShieldCheck,
  DotOutline,
  PenNib,
  FunnelSimple,
  SortAscending,
  SortDescending,
  Table,
  Ticket,
  ArrowUDownLeft,
  UserRectangle,
  UserList,
  UserGear,
  Warning,
  Video,
  Eye,
  EyeSlash,
  BugBeetle,
  SplitVertical,
  ArrowsInSimple,
  Medal,
  Download,
  ChartBarHorizontal,
  Play,
  ArrowsClockwise,
  ClockClockwise,
  Wrench,
  Megaphone,
  TrendUp,
  KeyReturn,
} from '@phosphor-icons/react';

export const icons = {
  add: PlusCircle,
  ad: Megaphone,
  adjust: Wrench,
  apply: KeyReturn,
  arrowBack: CaretLeft,
  arrowEnd: ArrowLineRight,
  arrowForward: CaretRight,
  arrowStart: ArrowLineLeft,
  bug: BugBeetle,
  cancel: XCircle,
  chartHorizontal: ChartBarHorizontal,
  checkbox: CheckFat,
  checklist: ListChecks,
  close: X,
  collapse: ArrowsInSimple,
  copy: Copy,
  delete: Trash,
  done: CheckCircle,
  download: Download,
  edit: Pencil,
  expandLess: CaretUp,
  expandMore: CaretDown,
  facebook: FacebookLogo,
  feed: NewspaperClipping,
  file: FileText,
  files: Files,
  fileCSV: FileCsv,
  fileDownload: FileArrowDown,
  fileUpload: FileArrowUp,
  fileXLS: FileXls,
  filter: Funnel,
  forbidden: Prohibit,
  form: NotePencil,
  forum: Chats,
  group: Users,
  home: HouseLine,
  image: Image,
  info: Info,
  link: Link,
  location: MapPin,
  lock: Lock,
  login: SignIn,
  logout: SignOut,
  mail: Envelope,
  quality: Medal,
  menu: List,
  money: Money,
  order: Basket,
  partners: Handshake,
  password: LockKeyOpen,
  pause: Pause,
  payment: HandCoins,
  play: Play,
  process: ArrowsClockwise,
  product: Package,
  question: Question,
  resize: SplitVertical,
  retry: ArrowCounterClockwise,
  reviews: Star,
  scale: TrendUp,
  search: MagnifyingGlass,
  searchList: ListMagnifyingGlass,
  searchPerson: Detective,
  security: ShieldCheck,
  separator: DotOutline,
  sign: PenNib,
  sort: FunnelSimple,
  sortAsc: SortAscending,
  sortDesc: SortDescending,
  star: Star,
  status: ClockClockwise,
  table: Table,
  ticket: Ticket,
  undo: ArrowUDownLeft,
  user: UserRectangle,
  users: UserList,
  userSettings: UserGear,
  warning: Warning,
  video: Video,
  visibilityOn: Eye,
  visibilityOff: EyeSlash,
} as const;
